# Generated by Django 2.0.7 on 2018-08-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500)),
                ('contract_type', models.CharField(max_length=500)),
                ('contract_time', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=10000)),
                ('company', models.CharField(max_length=500)),
                ('service', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'parsing_data',
            },
        ),
    ]
