# Generated by Django 2.0.7 on 2018-08-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezpars', '0002_data_jobs_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_jobs',
            name='company',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='data_jobs',
            name='contract_time',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='data_jobs',
            name='contract_type',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='data_jobs',
            name='description',
            field=models.CharField(default='None', max_length=10000),
        ),
        migrations.AlterField(
            model_name='data_jobs',
            name='location',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='data_jobs',
            name='service',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='data_jobs',
            name='title',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='data_jobs',
            name='url',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
