# Generated by Django 2.0.7 on 2018-08-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezpars', '0003_auto_20180803_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_jobs',
            name='url',
            field=models.CharField(default='None', max_length=3000),
        ),
    ]
